/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();
        this.visibilidadeBotao(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoValor1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoValor2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoValor3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoValor4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoSaldo = new javax.swing.JTextField();
        btnovaConta = new javax.swing.JButton();
        txtDespesa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTroco = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Para Controle de Gastos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(campoValor1);
        campoValor1.setBounds(34, 121, 190, 34);

        jLabel1.setText("Entre com o 1° Valor:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(34, 86, 190, 29);

        jLabel2.setText("Entre com o 2° Valor:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(34, 166, 190, 29);
        jPanel1.add(campoValor2);
        campoValor2.setBounds(34, 201, 190, 34);

        jLabel3.setText("Entre com o 3° Valor:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(34, 246, 190, 29);
        jPanel1.add(campoValor3);
        campoValor3.setBounds(34, 281, 190, 34);

        jLabel4.setText("Entre com o 4° Valor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(34, 326, 190, 29);
        jPanel1.add(campoValor4);
        campoValor4.setBounds(34, 361, 190, 34);

        jLabel5.setText("Entre com o saldo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(34, 11, 110, 29);
        jPanel1.add(campoSaldo);
        campoSaldo.setBounds(34, 46, 190, 34);

        btnovaConta.setBackground(new java.awt.Color(0, 0, 102));
        btnovaConta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnovaConta.setForeground(new java.awt.Color(255, 255, 255));
        btnovaConta.setText("Nova Conta");
        btnovaConta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovaContaActionPerformed(evt);
            }
        });
        jPanel1.add(btnovaConta);
        btnovaConta.setBounds(290, 230, 260, 35);

        txtDespesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDespesa.setText("Despesa Total: $00,00");
        jPanel1.add(txtDespesa);
        txtDespesa.setBounds(280, 100, 210, 50);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(260, 0, 40, 540);

        txtTroco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTroco.setText("Troco: $00,00");
        jPanel1.add(txtTroco);
        txtTroco.setBounds(280, 160, 210, 50);

        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSaldo.setText("Saldo: $00,00");
        jPanel1.add(txtSaldo);
        txtSaldo.setBounds(280, 30, 210, 50);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Realizar Cálculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(34, 406, 190, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(593, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovaContaActionPerformed
        visibilidadeBotao(false);
        limparCampos();
    }//GEN-LAST:event_btnovaContaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        realizarCalculo();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnovaConta;
    private javax.swing.JTextField campoSaldo;
    private javax.swing.JTextField campoValor1;
    private javax.swing.JTextField campoValor2;
    private javax.swing.JTextField campoValor3;
    private javax.swing.JTextField campoValor4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtDespesa;
    private javax.swing.JLabel txtSaldo;
    private javax.swing.JLabel txtTroco;
    // End of variables declaration//GEN-END:variables

    private void visibilidadeBotao(boolean visibilidadeBotaoNovo){
        if (visibilidadeBotaoNovo == true) {
            btnovaConta.setVisible(true);
        }else{
            btnovaConta.setVisible(false);
        }
    }
    private void verificarCampoVazio(){
        if (campoValor1.getText().isEmpty()) {
            campoValor1.setText("0");
        }
        if (campoValor2.getText().isEmpty()) {
            campoValor2.setText("0");
        }
        if (campoValor3.getText().isEmpty()) {
            campoValor3.setText("0");
        }
        if (campoValor4.getText().isEmpty()) {
            campoValor4.setText("0");
        }
    }
    
    private void realizarCalculo() {
        this.verificarCampoVazio();
        
        if (campoSaldo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Entre com o Saldo.");
        }
        
        double valor1 = Double.parseDouble(campoValor1.getText().replace(",", "."));
        double valor2 = Double.parseDouble(campoValor2.getText().replace(",", "."));
        double valor3 = Double.parseDouble(campoValor3.getText().replace(",", "."));
        double valor4 = Double.parseDouble(campoValor4.getText().replace(",", "."));
        
        double resultadoSomatorias = valor1 + valor2 + valor3 + valor4;
        double saldo = Double.parseDouble(campoSaldo.getText().replace(",", "."));
        double resultadoFinal = (resultadoSomatorias - saldo) * -1;

        if (saldo < resultadoSomatorias){
            double valorNegativo = resultadoFinal * -1;
            txtTroco.setText("Você ficou Devendo $" + String.format("%.2f", valorNegativo).replace(".", ","));
            txtTroco.setForeground(Color.red);
        } else {
            txtTroco.setText("Troco: $" + String.format("%.2f", resultadoFinal).replace(".", ","));
            txtTroco.setForeground(new Color(0,82,66));
        }
        txtDespesa.setText("Despesa Total: $" + String.format("%.2f", resultadoSomatorias).replace(".", ","));  
        txtSaldo.setText("Saldo: $" + String.format("%.2f", saldo).replace(".", ","));
        
        this.visibilidadeBotao(true);
    }
    
    private void limparCampos(){
        
        campoSaldo.setText(null);
        campoValor1.setText(null);
        campoValor2.setText(null);
        campoValor3.setText(null);
        campoValor4.setText(null);
        
        txtSaldo.setText("Saldo: $00,00");
        txtDespesa.setText("Despesa Total: $00,00");
        txtTroco.setText("Troco: $00,00");
        
        txtTroco.setForeground(Color.BLACK);
    }
}
